apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: my-app
    # Add repo to point to the local chart directory
    repo: ./helm
    version: 0.1.0
    releaseName: my-app-release
    namespace: my-app
    valuesInline:
      replicaCount: 2
      image:
        repository: nginx
        tag: "1.25"
    includeCRDs: false
